### ISSUE TITLE
Unable to Modify Derived Stats Without Rerunning Python Core

### ISSUE THREAD

**Issue by yql5510718** [Litz-Lab/Scarab-infra#8]
I'm using the derive_stat function in scarab_stats/scarab_stats.py to add derived statistics. While this successfully creates the derived stats, our current setup does not allow me to modify them once they are loaded.

If I want to change the function or equation used to calculate the derived stat after the initial call, I cannot simply update the existing derived stat entry. Instead, I am forced to rerun the entire Python core, which involves deleting all variables, reloading the experiments, and then re-adding the modified derived stat. This process is inefficient and cumbersome.

Request:
It would be helpful if there were a way to modify or update derived stats without needing to restart the entire Python environment. Is there a solution to make this process more flexible?

**Comment by 5surim** [comment]
Hi @FlyingFish800 

Could you have a look at this issue?

Thanks,
Surim

**Comment by FlyingFish800** [comment]
In the above pull request I implemented the ability to overwrite the value of a stat with an optional parameter of derive_stat. By setting overwrite=True in the derive_stat function call this functionality can now be achieved.
